export default Object.freeze({
  HOME: "HomeScreen",
  CETACEANS: "CetaceansScreen",
  MAP: "MapScreen",
  USER_PROFILE: "ProfileScreen",
  FEATURE: "Features",
  SETTINGS: "Settings",
  ABOUT: "About",
  ACCOUNT: "Account",
  PASSWORD: "Password",
  DELETE_ACCOUNT: "DeleteAccount",
  USERNAME: "Username",
  CETACEAN_PROFILE: "CetaceansProfile",
  WELCOME: "Welcome",
  REGISTER: "Rgister",
  LOGIN: "Login",
  FORGOT_PASSWORD: "ForgotPassword",
});
